export const validations = {
  email_exists: 'email.exists',
  email_not_valid: 'email.not_valid',
  email_not_exists: 'email.not_exists',
  password_not_correct: 'password.not_correct',
  user_name_exists: 'user_name.exists',
  user_name_not_exists: 'user_name.not_exists',
  user_name_not_correct: 'user_name.not_correct',
  phone_number_exists: 'phone_number.exists',
  phone_number_not_exists: 'phone_number.not_exists',
  phone_number_not_correct: 'phone_number.not_correct',
  file_type_not_allowed: "file.type_not_allowed",
  file_size_exceeded: "file.size_exceeded",
  file_not_found: "file.not_found",
  file_not_recognized: "file.not_recognized",
  file_upload_success: "file.upload_success",
  file_upload_failed: "file.upload_failed",
  file_delete_success: "file.delete_success",
  file_delete_failed: "file.delete_failed",
  file_download_success: "file.download_success",
  file_download_failed: "file.download_failed",
  password_min_length: "password.min_length",
  password_max_length: "password.max_length",
  password_special_characters: "password.special_characters",
};
